version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge
