services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 8000
    environment:
      - LM_API_BASE_URL=${LM_API_BASE_URL:-http://host.docker.internal:5001/v1}
      - RUNPOD_API_KEY=${RUNPOD_API_KEY:?RUNPOD_API_KEY is required}
      - RUNPOD_ENDPOINT_URL=${RUNPOD_ENDPOINT_URL}
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
    networks:
      - app
    container_name: backend

  nginx:
    image: nginx:alpine
    ports:
      - "8503:8503"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - frontend
    networks:
      - app
    container_name: nginx

networks:
  app:
    driver: bridge
